# Generated by Django 6.0.3 on 2026-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthconsultation',
            name='farmer_note',
            field=models.TextField(),
        ),
    ]
