# Generated by Django 6.0.3 on 2026-03-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_animal_purchase_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='healthconsultation',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='healthconsultation',
            old_name='farmer_note',
            new_name='symptoms',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='last_vaccination_date',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='healthconsultation',
            name='doctor_prescription',
        ),
        migrations.RemoveField(
            model_name='healthconsultation',
            name='status',
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tag_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('doctor', 'Doctor')], default='farmer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MilkRecord',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
