# Generated by Django 6.0.3 on 2026-03-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconsultation',
            name='doctor_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthconsultation',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthconsultation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
