# Generated by Django 6.0.3 on 2026-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_animal_category_alter_animal_tag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='last_vaccination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('hen', 'Hen'), ('duck', 'Duck'), ('bird', 'Bird')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
