# Generated by Django 6.0.1 on 2026-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_animal_last_vaccination_alter_animal_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthconsultation',
            name='animal',
        ),
        migrations.AddField(
            model_name='healthconsultation',
            name='animal_reg_id',
            field=models.CharField(default=0, help_text='পশুর রেজিঃ আইডি লিখুন', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthconsultation',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='health_reports/'),
        ),
        migrations.AlterField(
            model_name='healthconsultation',
            name='symptoms',
            field=models.TextField(verbose_name='সমস্যা বা লক্ষণ (SMS)'),
        ),
    ]
