# Generated by Django 6.0.3 on 2026-03-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_healthconsultation_animal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthconsultation',
            name='animal_reg_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='healthconsultation',
            name='symptoms',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='DailyFarmDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('animal_sold_count', models.IntegerField(default=0)),
                ('animal_sold_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('milk_liters', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('milk_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('egg_count', models.IntegerField(default=0)),
                ('egg_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meat_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meat_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
