# Generated by Django 6.0.3 on 2026-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_healthconsultation_animal_reg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfarmdiary',
            old_name='egg_price',
            new_name='income_amount',
        ),
        migrations.RenameField(
            model_name='dailyfarmdiary',
            old_name='meat_kg',
            new_name='labor_cost',
        ),
        migrations.RenameField(
            model_name='dailyfarmdiary',
            old_name='meat_price',
            new_name='other_cost',
        ),
        migrations.RenameField(
            model_name='dailyfarmdiary',
            old_name='milk_liters',
            new_name='vaccine_cost',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='animal_sold_count',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='egg_count',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='milk_price',
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='category',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('hen', 'Hen'), ('duck', 'Duck')], default='cow', max_length=10),
        ),
    ]
