# Generated by Django 6.0.3 on 2026-04-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_egg_price_dailyfarmdiary_income_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='last_vaccination',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='animal_sold_price',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='healthconsultation',
            name='doctor_advice',
        ),
        migrations.RemoveField(
            model_name='healthconsultation',
            name='report_image',
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('hen', 'Hen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyfarmdiary',
            name='category',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('hen', 'Hen')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
