# Generated by Django 6.0.3 on 2026-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_vaccination_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='dailyfarmdiary',
            name='vaccine_cost',
        ),
        migrations.AddField(
            model_name='animal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='egg_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='meat_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='medicine_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='milk_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('doctor', 'Doctor')], default='farmer', max_length=10),
        ),
    ]
