# Generated by Django 6.0.3 on 2026-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_animal_age_remove_animal_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='last_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
