# Generated by Django 6.0.3 on 2026-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_animal_last_vaccination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
