# Generated by Django 6.0.3 on 2026-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_animal_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('hen', 'Hen'), ('duck', 'Duck')], max_length=10),
        ),
    ]
