# Generated by Django 6.0.5 on 2026-05-24 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_location_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('hen', 'Hen'), ('duck', 'Duck')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'category')},
            },
        ),
        migrations.AddField(
            model_name='dailyfarmdiary',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='accounts.animalgroup'),
        ),
    ]
