# Generated by Django 6.0.5 on 2026-05-24 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_backfill_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyfarmdiary',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', False), ('animal__isnull', False), _negated=True), name='diary_group_xor_animal'),
        ),
    ]
